# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PFDevelopKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PFDevelopKit
  pod 'MBProgressHUD'
  pod 'SVProgressHUD'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'YYImage'
  pod 'YYWebImage'
  pod 'ReactiveObjC'    # RAC
  pod 'AFNetworking'
  

  target 'PFDevelopKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PFDevelopKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
